export const categories = [
  "Todas",
  "Contaminación del Aire",
  "Contaminación del Agua",
  "Contaminación del Suelo",
  "Cambio Climático",
  "Desastres Ambientales",
  "Politicas Ambientales",
  "Reciclaje",
];

export const districts = [
  "Alto Selva Alegre",
  "Arequipa",
  "Cayma",
  "Cerro Colorado",
  "Characato",
  "Chiguata",
  "Jacobo Hunter",
  "José Luis Bustamante y Rivero",
  "La Joya",
  "Mariano Melgar",
  "Miraflores",
  "Mollebaya",
  "Paucarpata",
  "Pocsi",
  "Polobaya",
  "Quequeña",
  "Sabandía",
  "Sachaca",
  "San Juan de Siguas",
  "San Juan de Tarucani",
  "Santa Isabel de Siguas",
  "Santa Rita de Siguas",
  "Socabaya",
  "Tiabaya",
  "Uchumayo",
  "Vitor",
  "Yanahuara",
  "Yarabamba",
  "Yura",
];
